# Generated by Django 5.2.6 on 2025-09-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CLABE', 'CLABE'), ('CARD', 'Card'), ('ACCOUNT', 'Account')], max_length=16)),
                ('value', models.CharField(max_length=32)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner', 'kind', '-updated_at'),
                'indexes': [models.Index(fields=['owner', 'kind'], name='bank_detail_owner_i_305bd4_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'kind'), name='uniq_bankdetail_owner_kind')],
            },
        ),
    ]
