# Generated by Django 5.2.6 on 2025-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_name_source',
            field=models.CharField(choices=[('AUTO', 'Auto-detected'), ('MANUAL', 'Manual')], default='AUTO', max_length=8),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='brand',
            field=models.CharField(blank=True, choices=[('VISA', 'VISA'), ('MASTERCARD', 'MasterCard'), ('OTHER', 'Other')], max_length=16),
        ),
    ]
