# Generated by Django 5.2.7 on 2025-10-06 21:33

from django.db import migrations


def update_brand_values(apps, schema_editor):
    """
    Actualiza los valores de brand a case-sensitive:
    VISA -> Visa
    MASTERCARD -> MasterCard
    OTHER -> Other
    """
    BankDetails = apps.get_model('bank_details', 'BankDetails')
    
    # Actualizar VISA a Visa
    BankDetails.objects.filter(brand='VISA').update(brand='Visa')
    
    # Actualizar MASTERCARD a Mastercard
    BankDetails.objects.filter(brand='MASTERCARD').update(brand='MasterCard')
    
    # Actualizar OTHER a Other
    BankDetails.objects.filter(brand='OTHER').update(brand='Other')


def reverse_brand_values(apps, schema_editor):
    """
    Revierte los valores de brand al formato anterior (mayúsculas)
    """
    BankDetails = apps.get_model('bank_details', 'BankDetails')
    
    # Revertir Visa a VISA
    BankDetails.objects.filter(brand='Visa').update(brand='VISA')
    
    # Revertir Mastercard a MASTERCARD
    BankDetails.objects.filter(brand='MasterCard').update(brand='MASTERCARD')
    
    # Revertir Other a OTHER
    BankDetails.objects.filter(brand='Other').update(brand='OTHER')


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0002_bankdetails_bank_code_bankdetails_bank_name_source_and_more'),
    ]

    operations = [
        migrations.RunPython(update_brand_values, reverse_brand_values),
    ]
