# Generated by Django 5.2.6 on 2025-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0003_update_brand_case_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='brand',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Other', 'Other')], max_length=16),
        ),
    ]
