# Generated by Django 5.2.7 on 2025-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0004_alter_bankdetails_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='phone',
            field=models.CharField(blank=True, help_text='Registra tu numero para poder recibir tus comprobantes de pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='kind',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('CLABE', 'CLABE'), ('CARD', 'Card'), ('ACCOUNT', 'Account')], max_length=16),
        ),
    ]
