# Generated by Django 5.2.6 on 2025-09-30 16:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=32, unique=True, validators=[accounts.models.validate_public_slug]),
        ),
    ]
