# Generated by Django 5.2.7 on 2025-10-24 20:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, validators=[accounts.models.validate_public_slug]),
        ),
    ]
